name: Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Syntax Check
        run: |
          python -m py_compile audio_transcriber.py web_server.py key_slide_extractor.py
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
